swagger: "2.0"
info:
  title: Human Resource Management System
  contact:
    email: dothienbinh13@gmail.com
  version: 1.0.0
  servers:
    - url: http://localhost:3000/
  tags:
    - name: users
      description: Everythong about users
    - name: jobs
      description: Everythong about job form
    - name: reviews
      description: Everythong about review form
paths:
  /user/login:
    post:
      tags:
        - users
      summary: get all users
      description: return all users
      operationId: "addPet"
      security:
        - jwt: []
      responses:
        200:
          description: OK
